/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        Graph<String> graph=new Graph<String>();


        Graphs<String> graphs = new Graphs<String>();
        Vertex a = graphs.addVertex("O");
       Vertex b =  graphs.addVertex("B");
        Vertex c = graphs.addVertex("A");
        Vertex d = graphs.addVertex("D");
        Vertex A = graphs.addVertex("A");

        graphs.addEdge(a,b,true);
        graphs.addEdge(a,c,true);
        graphs.addEdge(c,d,true);
        graphs.addEdge(b,d,true);
        graphs.addEdge(A,d,true);


//        System.out.println(graph.breadthFirst(a));

        Graphs<String> graphs1 = new Graphs<String>();

//
//        Vertex[] trip2 = new Vertex[] {a,b};
//        Vertex[] trip3 = new Vertex[] {c,d,A};
//        System.out.println(graph1.businessTrip(graph,trip2));

//        TreeTest<Integer> treeTest=new TreeTest<Integer>();
//
//        treeTest.insert(7);
//        treeTest.insert(5);
//        treeTest.insert(15);
//        treeTest.insert(4);
//        treeTest.insert(12);
//
//        System.out.println( treeTest.toString());


        System.out.println("******************** Depth First");



//        System.out.println(graphs.depthFirst(a));
        System.out.println(graphs.depthFirst(a));













//
//        graph.addEdge(graph.addVertex("O"), graph.addVertex("B"),true);
//        graph.addEdge(graph.addVertex("O"), graph.addVertex("A"),true);
//        graph.addEdge( graph.addVertex("D"),graph.addVertex("A"),true);


//        System.out.println(graph.toString());

//        graph.breadthFirst(a);





    }

}
