/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void insertTest(){
        LinkedList<Integer> list=new LinkedList<Integer>();


        list.insert(4);
        list.insert(8);
        list.insert(7);
        list.insert(9);
        list.insert(10);
        assertEquals("{10}=>{9}=>{7}=>{8}=>{4}=>NULL!",list.Stringing(),"it should return these numbers {10}=>{9}=>{7}=>{8}=>{4}=>NULL! ");

    }
    @Test void includesTest(){
        LinkedList<Integer> list=new LinkedList<Integer>();
        list.insert(5);

        assertTrue(list.includes(5),"it should return the new number");
    }
}
