/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void addingTest(){

        HashTable newHash=new HashTable(10);
        newHash.add("hello","this is hello");
        assertEquals(true,newHash.contains("hello"));

    }
    @Test void gettingTest(){

        HashTable newHash=new HashTable(10);
        newHash.add("hello","this is hello");
        assertEquals("this is hello",newHash.get("hello"));

    }
    @Test void nullTest(){

        HashTable newHash=new HashTable(10);

        assertEquals(null,newHash.get("wow"));

    }

    @Test void collisionTest(){

        HashTable newHash=new HashTable(10);
        newHash.add("a","first");
        newHash.add("W","second");


        assertEquals("first",newHash.nodes[7].value);
        assertEquals("second",newHash.nodes[7].next.value);

    }

    @Test void collisionGetTest(){

        HashTable newHash=new HashTable(10);
        newHash.add("a","first");
        newHash.add("W","second");


        assertEquals("first",newHash.get("a"));
        assertEquals("second",newHash.get("W"));


    }


    @Test void hashingTest(){

        HashTable newHash=new HashTable(10);


        assertEquals(7,newHash.hash("a"));



    }

    @Test void repeatedWordTest(){
        HashMapWords hashMapWords=new HashMapWords();

        String word1="Once upon a time, there was a brave princess who...";

        assertEquals("a",hashMapWords.repeatWord(word1));

        String word2 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        assertEquals("summer",hashMapWords.repeatWord(word2));

        String word3="there is no repated word";
        assertNull(hashMapWords.repeatWord(word3));
    }

    @Test void emptyTreeTest(){

        TreeIntersection treeIntersectionHash = new TreeIntersection();


        assertNull(treeIntersectionHash.root);

    }


    @Test void preOrderTest(){
        TreeNode Tree1 = new TreeNode();
        Tree1.root = new TreeNode(150);
        Tree1.root.left = new TreeNode(100);
        Tree1.root.left.left = new TreeNode(75);
        Tree1.root.left.right = new TreeNode(160);
        Tree1.root.left.right.left = new TreeNode(125);
        Tree1.root.left.right.right = new TreeNode(175);
        Tree1.root.right = new TreeNode(250);
        Tree1.root.right.left = new TreeNode(200);
        Tree1.root.right.right = new TreeNode(350);
        Tree1.root.right.right.left = new TreeNode(300);
        Tree1.root.right.right.right = new TreeNode(500);

        TreeIntersection treeIntersectionHash = new TreeIntersection();


        assertEquals(treeIntersectionHash.preOrder(Tree1.root),treeIntersectionHash.hashMap);

        assertNotNull(treeIntersectionHash.preOrder(Tree1.root));




    }

    @Test void treeInsertionTest(){
        TreeNode Tree1 = new TreeNode();
        Tree1.root = new TreeNode(150);
        Tree1.root.left = new TreeNode(100);
        Tree1.root.left.left = new TreeNode(75);
        Tree1.root.left.right = new TreeNode(160);
        Tree1.root.left.right.left = new TreeNode(125);
        Tree1.root.left.right.right = new TreeNode(175);
        Tree1.root.right = new TreeNode(250);
        Tree1.root.right.left = new TreeNode(200);
        Tree1.root.right.right = new TreeNode(350);
        Tree1.root.right.right.left = new TreeNode(300);
        Tree1.root.right.right.right = new TreeNode(500);

        TreeNode Tree2 = new TreeNode();
        Tree2.root = new TreeNode(42);
        Tree2.root.left = new TreeNode(100);
        Tree2.root.left.left = new TreeNode(15);
        Tree2.root.left.right = new TreeNode(160);
        Tree2.root.left.right.left = new TreeNode(125);
        Tree2.root.left.right.right = new TreeNode(175);
        Tree2.root.right = new TreeNode(600);
        Tree2.root.right.left = new TreeNode(200);
        Tree2.root.right.right = new TreeNode(350);
        Tree2.root.right.right.left = new TreeNode(4);
        Tree2.root.right.right.right = new TreeNode(500);

        TreeIntersection treeIntersectionHash = new TreeIntersection();

        assertEquals("[100, 160, 125, 175, 200, 350, 500]",treeIntersectionHash.treeInsertion(Tree1, Tree2).toString());
        assertNotNull(treeIntersectionHash.treeInsertion(Tree1, Tree2));

    }







}
