/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        HashTable newHash=new HashTable(10);

        newHash.add("hello","this is hello");
        newHash.add("hi","from other world");
//        newHash.hash("hello");




//
//        System.out.println(newHash.get("hello"));
//        System.out.println(newHash.get("hi"));
//        System.out.println(newHash.contains("hi"));

        newHash.add("a","first");
        System.out.println(newHash.get("a"));
        System.out.println(newHash.hash("a"));
       newHash.add("W","second");

        System.out.println(newHash.hash("W"));
       System.out.println(newHash.nodes[7].value);
        System.out.println(newHash.nodes[7].next.value);



    }


}
