/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

@Test
    public void testSort() {
    InsertionSort insertionSort = new InsertionSort();

    int[] arr = {8 , 4 , 23 , 42 , 16 , 15 };

    assertEquals("[ 4, 8, 15, 16, 23, 42]", Arrays.toString(insertionSort.insertionSort(arr)));
}

    @Test
    public void mergeSortTest() {
        MergeSort mergingSort=new MergeSort();

        int[] arr = {8 , 4 , 23 , 42 , 16 , 15 };

        assertEquals("[ 4, 8, 15, 16, 23, 42]", Arrays.toString(mergingSort.mergeSort(arr)));
    }
    @Test
    public void quickSortTest() {

        QuickSort quickSorts=new QuickSort();

        int[] arr = {8 , 4 , 23 , 42 , 16 , 15 };

        assertEquals("[ 4, 8, 15, 16, 23, 42]",Arrays.toString(quickSorts.quickSort(arr, 0, arr.length-1)));

        assertNotNull(Arrays.toString(quickSorts.quickSort(arr, 0, arr.length-1)));
    }
}
